server:
  error:
    whitelabel:
      enabled: false
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?createDatabaseIfNotExist=true
    username: root
    password: Bearsfan580!
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    org.springframework: ERROR
    securitydemo: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: com/jschwery/securitydemo/log/errorlog.txt


